import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, CalendarDays, Camera, ChevronRight, Heart, Search, ShieldCheck, Sparkles, Star, Tag, TrendingUp, UserRound, Wallet } from 'lucide-react'
import { AuthPanel } from './components/AuthPanel'
import { BookingModal } from './components/BookingModal'
import { supabase } from './lib/supabase'

type Category = 'Todos' | 'Vestidos' | 'Social' | 'Casual' | 'Masculino' | 'Infantil' | 'Esportivo'
type Item = { id:number; title:string; category:Exclude<Category,'Todos'>; size:string; price:number; rating:number; image:string; owner:string; days:number }
const categories:Category[]=['Todos','Vestidos','Social','Casual','Masculino','Infantil','Esportivo']
const items:Item[]=[
{id:1,title:'Vestido Midi Elegance',category:'Vestidos',size:'M',price:89,rating:4.9,image:'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=900&q=80',owner:'Ana',days:3},
{id:2,title:'Blazer Alfaiataria Premium',category:'Social',size:'G',price:75,rating:4.8,image:'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=900&q=80',owner:'Lucas',days:2},
{id:3,title:'Look Street Essential',category:'Casual',size:'M',price:55,rating:4.7,image:'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=80',owner:'Marina',days:3},
{id:4,title:'Terno Executivo Moderno',category:'Masculino',size:'48',price:120,rating:5,image:'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80',owner:'Rafael',days:2},
{id:5,title:'Vestido Festa Aurora',category:'Vestidos',size:'P',price:110,rating:4.9,image:'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=900&q=80',owner:'Julia',days:4},
{id:6,title:'Jaqueta Urban',category:'Casual',size:'G',price:65,rating:4.8,image:'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=900&q=80',owner:'Diego',days:3},]

function App(){
 const [category,setCategory]=useState<Category>('Todos'); const [search,setSearch]=useState(''); const [favorites,setFavorites]=useState<number[]>([]); const [authOpen,setAuthOpen]=useState(false); const [authenticated,setAuthenticated]=useState(false); const [bookingItem,setBookingItem]=useState<Item|null>(null)
 useEffect(()=>{ if(!supabase) return; supabase.auth.getSession().then(({data})=>setAuthenticated(Boolean(data.session))); const {data}=supabase.auth.onAuthStateChange((_event,session)=>setAuthenticated(Boolean(session))); return()=>data.subscription.unsubscribe() },[])
 const filteredItems=useMemo(()=>items.filter(item=>{const match=category==='Todos'||item.category===category;const q=search.toLowerCase().trim();return match&&(!q||`${item.title} ${item.category} ${item.owner}`.toLowerCase().includes(q))}),[category,search])
 const toggleFavorite=(id:number)=>setFavorites(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id])
 return <div className="app-shell">
  <header className="topbar"><div className="container nav"><div className="brand"><span className="brand-mark">C</span><span>Closet<span>Share</span></span></div><nav className="nav-links"><a href="#explorar">Explorar</a><a href="#como-funciona">Como funciona</a><a href="#meu-closet">Meu Closet</a></nav><button className="avatar-btn" onClick={()=>setAuthOpen(true)}><UserRound size={18}/> {authenticated?'Minha conta':'Entrar'}</button></div></header>
  <main>
   <section className="hero"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><Sparkles size={15}/> A nova economia do seu guarda-roupa</div><h1>Use mais.<br/><em>Compre menos.</em></h1><p>Alugue peças incríveis de pessoas reais ou transforme seu closet em uma nova fonte de renda.</p><div className="hero-actions"><a className="btn primary" href="#explorar">Explorar peças <ArrowRight size={17}/></a><button className="btn ghost" onClick={()=>setAuthOpen(true)}>Ganhar com meu closet</button></div><div className="trust-row"><span><ShieldCheck size={16}/> Pessoas verificadas</span><span><Star size={16}/> Avaliações reais</span><span><Wallet size={16}/> Pagamento seguro</span></div></div><div className="hero-visual"><img src={items[0].image} alt="Moda para aluguel"/><div className="floating-card income"><TrendingUp size={17}/><div><strong>R$ 1.240</strong><small>renda estimada / ano</small></div></div><div className="floating-card score"><span className="score-ring">94</span><div><strong>Rental Score</strong><small>Excelente oportunidade</small></div></div></div></div></section>
   <section className="section" id="explorar"><div className="container"><div className="section-heading"><div><span className="kicker">DESCUBRA</span><h2>Peças para todos os momentos</h2><p>Do evento especial ao look de todos os dias.</p></div><a className="text-link" href="#explorar">Ver catálogo completo <ChevronRight size={17}/></a></div><div className="search-row"><div className="search-box"><Search size={19}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Busque por peça, estilo ou ocasião..."/></div><div className="categories">{categories.map(cat=><button key={cat} className={category===cat?'active':''} onClick={()=>setCategory(cat)}>{cat}</button>)}</div></div><div className="item-grid">{filteredItems.map(item=><article className="item-card" key={item.id}><div className="item-image"><img src={item.image} alt={item.title}/><button className={`favorite ${favorites.includes(item.id)?'liked':''}`} onClick={()=>toggleFavorite(item.id)} aria-label="Favoritar"><Heart size={18} fill={favorites.includes(item.id)?'currentColor':'none'}/></button><span className="rental-days"><CalendarDays size={13}/> {item.days} dias</span></div><div className="item-body"><div className="item-meta"><span>{item.category}</span><span>• {item.size}</span></div><h3>{item.title}</h3><div className="owner"><span className="owner-avatar">{item.owner[0]}</span><span>por {item.owner}</span><span className="rating"><Star size={14} fill="currentColor"/> {item.rating}</span></div><div className="price"><strong>R$ {item.price}</strong><span>/ período</span><button onClick={()=>setBookingItem(item)}>Alugar</button></div></div></article>)}</div></div></section>
   <section className="income-section" id="meu-closet"><div className="container income-grid"><div><span className="kicker">SEU CLOSET PODE RENDER</span><h2>Roupas paradas<br/>viram <em>renda.</em></h2><p>Publique peças que você já tem, defina preço e disponibilidade e deixe o ClosetShare cuidar do resto.</p><div className="benefits"><span><Camera size={18}/> Publique com uma foto</span><span><Tag size={18}/> Sugestão inteligente de preço</span><span><Wallet size={18}/> Receba após cada aluguel</span></div><button className="btn light" onClick={()=>setAuthOpen(true)}>Começar a monetizar <ArrowRight size={17}/></button></div><div className="calculator"><div className="calc-top"><span>Closet Income</span><TrendingUp size={19}/></div><div className="calc-number">R$ 3.840<small>/ ano estimado</small></div><div className="calc-row"><span>12 peças disponíveis</span><strong>+ R$ 320/mês</strong></div><div className="progress"><span/></div><p>Potencial estimado com base em peças, preço e ocupação. <u>Saiba como calculamos.</u></p></div></div></section>
   <section className="steps section" id="como-funciona"><div className="container"><div className="section-heading centered"><div><span className="kicker">SIMPLES PARA TODO MUNDO</span><h2>Do closet para o próximo look</h2></div></div><div className="step-grid"><div><span>01</span><h3>Publique</h3><p>Fotografe sua peça, conte sobre ela e defina sua disponibilidade.</p></div><div><span>02</span><h3>Conecte</h3><p>Quem precisa encontra sua peça, reserva e combina a entrega.</p></div><div><span>03</span><h3>Alugue</h3><p>Entregue, acompanhe o aluguel e receba seu dinheiro com segurança.</p></div></div></div></section>
  </main>
  <footer><div className="container footer-inner"><div className="brand"><span className="brand-mark">C</span><span>Closet<span>Share</span></span></div><p>Moda que circula. Valor que volta.</p><span>© 2026 ClosetShare</span></div></footer>
  {authOpen&&<AuthPanel onClose={()=>setAuthOpen(false)}/>} {bookingItem&&<BookingModal item={bookingItem} open={Boolean(bookingItem)} onClose={()=>setBookingItem(null)} authenticated={authenticated} onLogin={()=>setAuthOpen(true)}/>} 
 </div>
}
export default App
